# Generated by Django 6.0.6 on 2026-06-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tadbir nomi')),
                ('description', models.TextField(verbose_name='Tadbir haqida')),
                ('date', models.DateTimeField(verbose_name='Tadbir sanasi va vaqti')),
                ('location', models.CharField(max_length=255, verbose_name='Manzil')),
                ('capacity', models.PositiveIntegerField(verbose_name='Maksimal ishtirokchilar soni')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Tadbir rasmi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Tadbir holati')),
            ],
        ),
    ]
